name: check
on: [push]
jobs:
        check:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@master
                        - uses: nanasess/setup-chromedriver@master
                        - name: Check with Gradle
                          run: ./gradlew check
